### ISSUE TITLE
Not compatible with Decky loader

### ISSUE THREAD

**Issue by MisterrrX** [ILadis/ts3-qs4sd#1] opened 2023-01-13 07:08 UTC
When the Decky plugin loader is installed, this plugin will not show up in the sidebar. 

Thanks for the amazing work though!

**Comment by ILadis** [comment] 2023-01-15 18:30
I tried to setup a local development environment on my desktop PC with Decky Loader today. Unfortunately I'm forced to use the Steam Beta client at the moment or otherwise [`steam -gamepadui` won't work](https://github.com/ValveSoftware/steam-for-linux/issues/8916). It seems like Decky Loader is not working with the latest Steam Beta update yet, [see this issue](https://github.com/SteamDeckHomebrew/decky-loader/issues/339).

I'm coming back to this, once Decky Loader is working again.

**Comment by ILadis** [comment] 2023-01-20 22:08
Since Decky Loader is now working with the latest Steam Beta client, I tried running both Decky Loader and my TeamSpeak 3 Plugin on my development PC. At a first glance everything seems to be working as expected.

<details><summary>See this screenshot</summary>
<br>
<img src="https://user-images.githubusercontent.com/7196536/213813562-d181c8ec-6084-4fac-9fdb-8a36d78e2cd2.png">
</details>

Both the Decky Loader and TeamSpeak icons appear on the Quick Settings page.

Can you give me any more hints on how I could reproduce the issue?

**Comment by Neomerlinux** [comment] 2023-01-20 23:18
I just followed your installation instructions to the teeth and the icon also wont show up, but since I also use DeckyLoader and saw your screenshot above, I asume you have not tried it on the deck yourself. You are missing the keyboard button underneath the decky icon. I am guessing that there's a limit to visible buttons on the deck and Decky is allready using up the space where your TeamSpeak plugin would show up. I'm not a programmer, but that's the first that came to mind.

EDIT: By the way: great plugin! great work! I was wondering when someone was thinking about TeamSpeak.

**Comment by ILadis** [comment] 2023-01-21 14:45
Thanks @Neomerlinux for participating and sharing your details.

I tried it now on the Deck itself and it's still working for me. 
<details><summary>See this screenshot</summary>
<br>
<img src="https://user-images.githubusercontent.com/7196536/213871770-4c45a00b-a996-4f50-9d31-73c30aaf7e7a.jpg">
</details>

These were my steps:
1. Install the TeamSpeak plugin and Decky Loader from desktop mode
1. Return to desktop mode
1. Launch TeamSpeak
1. Open the Quick Settings page

You can try the latest development build of my plugin, but I don't think I changed anything important though. Download and extract [ts3-qs4sd-v0.4-dev.zip](https://github.com/ILadis/ts3-qs4sd/files/10472363/ts3-qs4sd-v0.4-dev.zip) and replace the old version on your Deck at:  
`/home/deck/.var/app/com.teamspeak.TeamSpeak/.ts3client/plugins`

**Comment by MisterrrX** [comment] 2023-01-21 15:20
Tried reinstalling following your installation instructions step by step, but it still doesn't showing up (also tried the development build you suggested).

**Comment by ILadis** [comment] 2023-01-21 23:32
Since I am not able to reproduce the issue, a logfile from your Deck might point us in the right direction.

It's a little tricky to get to said logfile and also requires a PC with a Chromium based browser.  
But this would be the steps:
1. Reboot or power on your Deck (don't launch Teamspeak yet)
2. On your PC launch Chromium and enter `chrome://inspect` in the URL bar
3. Click on the "Configure..."-button an enter the IP address of your Deck followed by `:8081`

<details><summary>See this screenshot; my Deck's IP address is <code>192.168.178.17</code></summary><img src="https://user-images.githubusercontent.com/7196536/213892062-76ef8b23-92f2-486b-acfb-3ee706b4e5cc.png"></details>

4. Once you've done that, you should see a "Remote Target"

<details><summary>See this screenshot</summary><img src="https://user-images.githubusercontent.com/7196536/213891988-dcb6d61d-af1e-437e-8faf-453c67b5dcde.png"></details>

5. Click on the "Inspect"-link for the `QuickAccess_uid2` tab which should open another window
7. Launch TeamSpeak on your Deck,  wait a few seconds, then close the application
8. On Chromium make sure to select the "Console"-tab, then right click and select "Save as..."

<details><summary>See this screenshot</summary><img src="https://user-images.githubusercontent.com/7196536/213893324-60aae1ee-7ca4-4d92-aee3-05ef1e45b585.png"></details>

9. Save the logfile to your PC and upload it here

If there aren't any visible errors, I could provide another development build with more log messages.

**Comment by fbnkrs** [comment] 2023-03-03 14:35
Having the same issue.

Why is your screenshot missing the help button in the quick access menu?

Maybe it is just because there is no space left.

**Comment by ILadis** [comment] 2023-03-03 16:36
Are you referring to the screenshot in [this reply](https://github.com/ILadis/ts3-qs4sd/issues/1#issuecomment-1399009984)?

But regardless, the help icon is never showing, once my plugin is active and that is expected behavior. Because my plugin replaces this spot in the quick access menu with the TeamSpeak icon.

I might spent some time during this weekend working on the issue. Maybe I am able to reproduce it this time.

**Comment by ILadis** [comment] 2023-03-03 20:14
Still not able to repdroduce.  
I used Decky Loader [v2.6.2](https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v2.6.2) and the Steam Deck stable update channel (OS Version 3.4.4, OS Build 20221228.1).

<details><summary>Screenshot</summary>

![20230303210650_1](https://user-images.githubusercontent.com/7196536/222816705-408ea05c-1e81-4da6-ba13-48640af77deb.jpg)

</details>

**Comment by fbnkrs** [comment] 2023-03-17 12:06
> But regardless, the help icon is never showing, once my plugin is active and that is expected behavior. Because my plugin replaces this spot in the quick access menu with the TeamSpeak icon.

Ah okay, good to know.

Unfortunately I am not able to get it working again.

Teamspeak icon does not show up.

Maybe there is some weird incompatibility with a specific decky loader plugin?

I use:
- ProtonDB Badges
- CSS Loader
- vibrantDeck
- KLang
- Audio Loader
- SteamGridDB
- Animation Changer

**Comment by LouisH99** [comment] 2023-06-01 20:17
Having the same problem will try to get the log when i got some time

**Comment by LouisH99** [comment] 2023-06-02 13:59
hear is the log you wanted 
[steamloopback.host-1685713018723.log](https://github.com/ILadis/ts3-qs4sd/files/11635982/steamloopback.host-1685713018723.log)

**Comment by ILadis** [comment] 2023-06-03 19:20
Thanks for providing the log file.

This looks like the bug I fixed just recently in commit 0029fbf. There is no release yet, but you can try [this development build](https://github.com/ILadis/ts3-qs4sd/files/11643530/ts3-qs4sd.so.zip). Should report as version 0.5-dev in TeamSpeak. Just unzip the file and install it as described in the [README.md](https://github.com/ILadis/ts3-qs4sd#installing).

<details><summary>Screenshot</summary>
<img src="https://github.com/ILadis/ts3-qs4sd/assets/7196536/4543de39-e172-4986-ad7a-27f8a0bc2111">
</details>

Let me know if this fixes your issue. I'm then going to publish a new release version.

**Comment by Hellangel1987** [comment] 2023-06-19 11:06
facing same issue with your new Version - plugin not showing up and also using decky loader 

ProtonDB Badges
CSS Loader
vibrantDeck
KLang
Audio Loader
SteamGridDB
Animation Changer

**Comment by tarikalmashni** [comment] 2023-06-20 12:33
Just came here to report the very same issue.
Already had Decky installed, then installed TS3 and your plugin step by step following your guide but the icon won't show up.

Apart from this bug, out of curiosity: Would be too much work for you to just release a DeckyLoader plugin?

**Comment by ILadis** [comment] 2023-06-20 16:40
I am definetly going to *convert* this into a DeckyLoader plugin. But this will take some time, because there is a lot of stuff I need to wrap my head around first.

This should also make the plugin accessible to more users since DeckyLoader is the defacto standard for doing Homebrew on the Steam Deck.

**Comment by Hellangel1987** [comment] 2023-06-20 17:36
thank you this makes sense - since this stuff is great on steamdeck playing with your friends via Teamspeak

**Comment by ILadis** [comment] 2023-07-09 16:51
I got the first DeckyLoder plugin version ready for testing.

In order to test this version:  
1. Copy the `ts3-qs4sd.so` file to: `/home/deck/.var/app/com.teamspeak.TeamSpeak/.ts3client/plugins`.
2. Then install the DeckyLoader plugin by moving the `ts3-qs4sd/` folder to the `plugins/` directory of your Decky installation.
3. Restart your Steam Deck, the plugin should then appear in your plugins list.

All files and folders mentioned can be found in this [plugin.zip](https://github.com/ILadis/ts3-qs4sd/files/11995663/plugin.zip).

**Edit**: Also note that the DeckyLoader plugin will now start TeamSpeak for you in the background. This means you do not need to start TeamSpeak manually anymore.

I am going to update the README with the new installation instructions and also publish a *official* release version next.

Screenshots:
![20230709184540_1](https://github.com/ILadis/ts3-qs4sd/assets/7196536/1cdfcba6-08d6-4af3-a5e3-707c1ecd1a5d)
![20230709184553_1](https://github.com/ILadis/ts3-qs4sd/assets/7196536/55d4a0e1-ce60-48e4-8946-615d18583180)

**Comment by ThaMighty90** [comment] 2023-07-11 21:32
Nice Job! The Decky plugin is working so much better than your previous version also Controller support for all the controls, yeah!!. 

One funny thing and I dont know if this is intended bevahiour or not but you can actually connect to a server through the QAM without launching Teamspeak beforehand but after that you cant launch teamspeak so it is constantly lurking in the background eating ressources.

What I also noticed is that the new plugin no longer grinds my deck to a hold once I close teamspeak.

**Comment by ILadis** [comment] 2023-07-11 21:53
Thanks for your feedback. Glad it's working for you.

I should have mentioned that you don't need to manually launch TeamSpeak anymore. The decky plugin will do that for you now.

As of now there would be no way to close TeamSpeak after you are done using it. Any suggestions on how this should be handled? Would it bother you if TeamSpeak would continue running in the background or would you rather have a method of closing it?

**Comment by Hellangel1987** [comment] 2023-07-12 07:11
what about some little button to start and kill Teamspeak "service?

> Thanks for your feedback. Glad it's working for you.
> 
> I should have mentioned that you don't need to manually launch TeamSpeak anymore. The decky plugin will do that for you now.
> 
> As of now there would be no way to close TeamSpeak after you are done using it. Any suggestions on how this should be handled? Would it bother you if TeamSpeak would continue running in the background or would you rather have a method of closing it?

**Comment by ThaMighty90** [comment] 2023-07-12 09:15
My thoughts exactly.

> what about some little button to start and kill Teamspeak "service?
> 
> > Thanks for your feedback. Glad it's working for you.
> > I should have mentioned that you don't need to manually launch TeamSpeak anymore. The decky plugin will do that for you now.
> > As of now there would be no way to close TeamSpeak after you are done using it. Any suggestions on how this should be handled? Would it bother you if TeamSpeak would continue running in the background or would you rather have a method of closing it?

**Comment by ILadis** [comment] 2023-07-13 20:10
I just released [version 0.6](https://github.com/ILadis/ts3-qs4sd/releases/tag/v0.6) of the plugin and updated the installation instructions. Since I received positive feedback on the development build (version `0.6-dev`) I consider this issue resolved. Feel free to open a new issues if you encounter any problems with the latest version.

**Closed as completed by ILadis** 2023-07-13 20:10 UTC

**Comment by Banyyk** [comment] 2023-08-09 06:45
i have a weird issue.
i followed the instructions (i guess) step by step and teamspeak is working fine on desktop mode.
when i change to gamemode and open the quickbar decky and the teamspeak plugin is showing up.
BUT i only get the teamspeak plugin without any controlls. i used your screenshot do demonstrate what iam talking about.
everything in the red square is missing.

![PmIMxWRaUB](https://github.com/ILadis/ts3-qs4sd/assets/141810471/93d8494a-d22e-4e47-a712-ed0eb16b7ecc)


so i just got the arrow to go back and nothing else.

edit: well, one more thing: at the top it does not say "Teamspeak 3" it just sas "TS3 Quick Access"

**Comment by ILadis** [comment] 2023-08-09 14:53
Since you also commented in the other issue #5, let's continue the discussion there.
